[package]
name = "gtfs-bin"
version = "0.0.1"
edition = "2024"
description = "Pre compute GTFS transit networks into memory mapped binary files. Features zero copy deserialization, RAPTOR ready structures, and instant server startup."
authors = ["Vincent Brodin <vincent.brodin21@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/vincbro/gtfs-bin"
keywords = [
  "gtfs",
]

[lib]
name = "gtfsbin"
path = "src/lib.rs"

[[bin]]
name = "gtfs-bin"
path = "src/main.rs"

[dependencies]
bytemuck = {version = "1.25.0", features = ["derive"] }
chrono = "0.4.44"
clap = { version = "4.5.60", features = ["derive"] }
gtfs-structures = { version = "0.47.0", default-features = false }
